In [3]:
import pandas as pd

In [24]:
def if_value_null(cell):
    if cell == "":
        return "Empty"
    else: 
        return cell

def if_value_null_zero(cell):
    if cell == "":
        return 0
    else: 
        return cell

def convert_nik_cell(cell):
    result = if_value_null(cell)
    return result

def convert_full_name_cell(cell):
    result = if_value_null(cell)
    return result

def convert_position_cell(cell):
    result = if_value_null(cell)
    return result

def convert_sex_cell(cell):
    result = if_value_null(cell)
    return result

def convert_joined_date_cell(cell):
    result = if_value_null(cell)
    return result

def convert_status_certification_cell(cell):
    result = if_value_null(cell)
    return result

def convert_associate_cell(cell):
    result = if_value_null_zero(cell)
    return result

def convert_specialist_cell(cell):
    result = if_value_null_zero(cell)
    return result

def convert_expert_cell(cell):
    result = if_value_null_zero(cell)
    return result

def convert_galaxy_master_cell(cell):
    result = if_value_null(cell)
    return result

def convert_man_power_active_cell(cell):
    result = if_value_null(cell)
    return result

def convert_npwp_cell(cell):
    result = if_value_null(cell)
    return result

def convert_bpjs_cell(cell):
    result = if_value_null(cell)
    return result

def convert_handphone1_cell(cell):
    result = if_value_null(cell)
    return result

def convert_handphone2_cell(cell):
    result = if_value_null_zero(cell)
    return result

def convert_email_cell(cell):
    return cell

def convert_district_cell(cell):
    result = if_value_null(cell)
    return result

def convert_state_cell(cell):
    result = if_value_null(cell)
    return result

def convert_region_cell(cell):
    result = if_value_null_zero(cell)
    return result

def convert_city_cell(cell):
    result = if_value_null(cell)
    return result

def convert_retail_hub_cell(cell):
    result = if_value_null(cell)
    return result

def convert_branch_cell(cell):
    result = if_value_null(cell)
    return result

def convert_rsm_area_cell(cell):
    result = if_value_null(cell)
    return result

def convert_direct_supervisor_cell(cell):
    result = if_value_null(cell)
    return result

df = pd.read_excel("files/data.xlsx", "Sheet1", index=1, converters={
    'NIK': convert_nik_cell,
    'Full Name': convert_full_name_cell,
    'Position': convert_position_cell,
    'Sex': convert_sex_cell,
    'Joined Date': convert_joined_date_cell,
    'Status Certification': convert_status_certification_cell,
    'Associate': convert_associate_cell,
    'Specialist': convert_specialist_cell,
    'Expert': convert_expert_cell,
    'Galaxy Master': convert_galaxy_master_cell,
    'Man Power Active': convert_man_power_active_cell,
    'NPWP': convert_npwp_cell,
    'BPJS': convert_bpjs_cell,
    'Handphone 1': convert_handphone1_cell,
    'Handphone 2': convert_handphone2_cell,
    'Email': convert_email_cell,
    'District': convert_district_cell,
    'State': convert_state_cell,
    'Region': convert_region_cell,
    'City': convert_city_cell,
    'Retail Hub': convert_retail_hub_cell,
    'Branch': convert_branch_cell,
    'RSM Area': convert_rsm_area_cell,
    'Direct Supervisor': convert_direct_supervisor_cell
})

In [25]:
df

,No,NIK,Full Name,Position,Sex,Joined Date,Status Certification,Associate,Specialist,Expert,...,Handphone 2,Email,District,State,Region,City,Retail Hub,Branch,RSM Area,Direct Supervisor
0,1,1234567,ANTON,MANAGER,L,20160311,EXPERT,0,0,0,...,123456789,anton@email.com,ROAD AREA,KOTA MADIUN,JAWA TIMUR,63121 MANGUHARJO,EAST JAVA 06,JAWA TIMUR 3,REGION EAST,AC-202020

In [26]:
df.to_excel("files/new.xlsx", sheet_name="Sheet1")

ImportError: No module named openpyxl.workbook